spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: mongo-diary-database
      port: 27017
      host: 192.168.0.144

logging:
  level:
    root: INFO
    com.vitanum: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


